# Generated by Django 4.2.5 on 2023-09-22 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='MeasurementPointReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('threshold_1', models.IntegerField()),
                ('threshold_2', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('overall_severity', models.CharField(max_length=10)),
                ('remarks', models.TextField(null=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.machine')),
                ('results', models.ManyToManyField(to='report.measurementpointreading')),
            ],
        ),
        migrations.CreateModel(
            name='MeasurementPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.machine')),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.standard')),
            ],
        ),
    ]
