# Generated by Django 4.2.5 on 2023-09-22 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='MeasurementPointReading',
        ),
        migrations.AlterField(
            model_name='report',
            name='results',
            field=models.ManyToManyField(to='report.reading'),
        ),
    ]
