# Generated by Django 4.2.5 on 2023-09-22 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_reading_delete_measurementpointreading_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reading',
            options={'managed': False},
        ),
    ]
