# Generated by Django 4.2.5 on 2023-09-22 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_alter_reading_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reading',
            options={'managed': True},
        ),
    ]
