# Generated by Django 4.2.5 on 2023-09-22 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_alter_reading_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='x_point',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reading',
            name='x_severity',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reading',
            name='y_point',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reading',
            name='y_severity',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reading',
            name='z_point',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reading',
            name='z_severity',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
    ]
