# Generated by Django 4.2.5 on 2023-09-22 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_reading_x_point_reading_x_severity_reading_y_point_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='measurement_point',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='report.measurementpoint'),
            preserve_default=False,
        ),
    ]
