# Generated by Django 4.2.5 on 2023-09-25 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0008_alter_report_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='x_point',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='reading',
            name='y_point',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='reading',
            name='z_point',
            field=models.PositiveIntegerField(),
        ),
    ]
