# Generated by Django 4.2.5 on 2023-09-25 06:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0009_alter_reading_x_point_alter_reading_y_point_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='x_point',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='reading',
            name='y_point',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='reading',
            name='z_point',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
